In [1]:
import pandas as pd

In [3]:
fruits = pd.read_table('fruit_data_with_colors.txt')

feature_names_fruits = ['height', 'width', 'mass', 'color_score']
X_fruits = fruits[feature_names_fruits]
y_fruits = fruits['fruit_label']
target_names_fruits = ['apple', 'mandarin', 'orange', 'lemon']

X_fruits_2d = fruits[['height', 'width']]
y_fruits_2d = fruits['fruit_label']

In [5]:
y_fruits.head()

0    1
1    1
2    1
3    2
4    2
Name: fruit_label, dtype: int64

In [6]:
X_fruits.head()

height  width  mass  color_score
0     7.3    8.4   192         0.55
1     6.8    8.0   180         0.59
2     7.2    7.4   176         0.60
3     4.7    6.2    86         0.80
4     4.6    6.0    84         0.79

In [7]:
y_fruits_2d.head()

0    1
1    1
2    1
3    2
4    2
Name: fruit_label, dtype: int64

In [8]:
X_fruits_2d.head()

height  width
0     7.3    8.4
1     6.8    8.0
2     7.2    7.4
3     4.7    6.2
4     4.6    6.0

## Linear Regression

In [9]:
from sklearn.linear_model import LogisticRegression
y_fruits_apple = y_fruits_2d == 1

In [11]:
y_fruits_apple.head()

0     True
1     True
2     True
3    False
4    False
Name: fruit_label, dtype: bool

In [12]:
X_fruits_2d.as_matrix()

/home/ayush/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


array([[ 7.3,  8.4],
       [ 6.8,  8. ],
       [ 7.2,  7.4],
       [ 4.7,  6.2],
       [ 4.6,  6. ],
       [ 4.3,  5.8],
       [ 4.3,  5.9],
       [ 4. ,  5.8],
       [ 7.8,  7.1],
       [ 7. ,  7.4],
       [ 7.3,  6.9],
       [ 7.6,  7.1],
       [ 7.1,  7. ],
       [ 7.7,  7.3],
       [ 7.3,  7.6],
       [ 7.1,  7.7],
       [ 7.5,  7.6],
       [ 7.6,  7.5],
       [ 7.1,  7.5],
       [ 7.2,  7.4],
       [ 7.5,  7.5],
       [ 7.4,  7.4],
       [ 7.1,  7.3],
       [ 7.9,  7.6],
       [ 9.4,  9. ],
       [ 9.2,  9.2],
       [ 9.2,  9.6],
       [ 9.2,  7.5],
       [ 7.1,  6.7],
       [ 7.4,  7. ],
       [ 7.5,  7.1],
       [ 8. ,  7.8],
       [ 7. ,  7.2],
       [ 8.1,  7.5],
       [ 7.8,  7.6],
       [ 7.9,  7.1],
       [ 7.6,  7.1],
       [ 7.3,  7.3],
       [ 7.8,  7.2],
       [ 7.4,  6.8],
       [ 7.5,  7.1],
       [ 8.2,  7.6],
       [ 7.2,  7.2],
       [10.3,  7.2],
       [10.5,  7.3],
       [ 9.2,  7.2],
       [10.2,  7.3],
       [ 9.7,

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = (
train_test_split(X_fruits_2d.as_matrix(),
                y_fruits_apple.as_matrix(),
                random_state = 0))

/home/ayush/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  This is separate from the ipykernel package so we can avoid doing imports until
/home/ayush/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  after removing the cwd from sys.path.


In [17]:
clf = LogisticRegression(C=100).fit(X_train, y_train)

In [18]:
print('Accuracy of Logistic regression classifier on training set: {:.2f}'
     .format(clf.score(X_train, y_train)))
print('Accuracy of Logistic regression classifier on test set: {:.2f}'
     .format(clf.score(X_test, y_test)))

Accuracy of Logistic regression classifier on training set: 0.77
Accuracy of Logistic regression classifier on test set: 0.73


## Support vector machines

### Linear SVM

In [20]:
from sklearn.datasets import make_classification
X_C2, y_C2 = make_classification(n_samples = 100, n_features=2,
                                n_redundant=0, n_informative=2,
                                n_clusters_per_class=1, flip_y = 0.1,
                                class_sep = 0.5, random_state=0)

In [22]:
from sklearn.svm import SVC
X_train, X_test, y_train, y_test = train_test_split(X_C2, y_C2, random_state = 0)
this_C = 1.0
clf = SVC(kernel = 'linear', C=this_C).fit(X_train, y_train)

In [25]:
from sklearn.datasets import load_breast_cancer
(X_cancer, y_cancer) = load_breast_cancer(return_X_y = True)
from sklearn.svm import LinearSVC
X_train, X_test, y_train, y_test = train_test_split(X_cancer, y_cancer, random_state = 0)

clf = LinearSVC().fit(X_train, y_train)
print('Breast cancer dataset')
print('Accuracy of Linear SVC classifier on training set: {:.2f}'
     .format(clf.score(X_train, y_train)))
print('Accuracy of Linear SVC classifier on test set: {:.2f}'
     .format(clf.score(X_test, y_test)))

Breast cancer dataset
Accuracy of Linear SVC classifier on training set: 0.83
Accuracy of Linear SVC classifier on test set: 0.81


## Multi-class classification with linear models

#### LinearSVC with M classes generates M one vs rest classifiers.

In [29]:
y_fruits_2d

0     1
1     1
2     1
3     2
4     2
5     2
6     2
7     2
8     1
9     1
10    1
11    1
12    1
13    1
14    1
15    1
16    1
17    1
18    1
19    1
20    1
21    1
22    1
23    1
24    3
25    3
26    3
27    3
28    3
29    3
30    3
31    3
32    3
33    3
34    3
35    3
36    3
37    3
38    3
39    3
40    3
41    3
42    3
43    4
44    4
45    4
46    4
47    4
48    4
49    4
50    4
51    4
52    4
53    4
54    4
55    4
56    4
57    4
58    4
Name: fruit_label, dtype: int64

In [31]:
from sklearn.svm import LinearSVC

X_train, X_test, y_train, y_test = train_test_split(X_fruits_2d, y_fruits_2d, random_state = 0)

clf = LinearSVC(C=5, random_state = 67).fit(X_train, y_train)
print('Coefficients:\n', clf.coef_) # 4 lines made,hence 4 classifiers are shown
print('Intercepts:\n', clf.intercept_)

Coefficients:
 [[-0.2632447   0.71355615]
 [-1.62923806  1.15817804]
 [ 0.03316693  0.28703901]
 [ 1.24224735 -1.63576356]]
Intercepts:
 [-3.2898795   1.19927347 -2.71574774  1.16108696]


## Kernelized SVM

In [33]:
from sklearn.datasets import make_classification, make_blobs
X_D2, y_D2 = make_blobs(n_samples = 100, n_features = 2, centers = 8,
                       cluster_std = 1.3, random_state = 4)
X_train, X_test, y_train, y_test = train_test_split(X_D2, y_D2, random_state = 0)

In [35]:
SVC().fit(X_train, y_train) ##default kernel is rbf

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [37]:
SVC(kernel = 'poly', degree = 3).fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='poly',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [38]:
## gamma and c are two variable parameters here

## Application of SVMs to a real dataset: unnormalized dat

In [39]:
from sklearn.svm import SVC
X_train, X_test, y_train, y_test = train_test_split(X_cancer, y_cancer,
                                                   random_state = 0)

clf = SVC(C=10).fit(X_train, y_train)
print('Breast cancer dataset (unnormalized features)')
print('Accuracy of RBF-kernel SVC on training set: {:.2f}'
     .format(clf.score(X_train, y_train)))
print('Accuracy of RBF-kernel SVC on test set: {:.2f}'
     .format(clf.score(X_test, y_test)))

Breast cancer dataset (unnormalized features)
Accuracy of RBF-kernel SVC on training set: 1.00
Accuracy of RBF-kernel SVC on test set: 0.63


## Application of SVMs to a real dataset: normalized data with feature preprocessing using minmax scaling

In [40]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

clf = SVC(C=10).fit(X_train_scaled, y_train)
print('Breast cancer dataset (normalized with MinMax scaling)')
print('RBF-kernel SVC (with MinMax scaling) training set accuracy: {:.2f}'
     .format(clf.score(X_train_scaled, y_train)))
print('RBF-kernel SVC (with MinMax scaling) test set accuracy: {:.2f}'
     .format(clf.score(X_test_scaled, y_test)))

Breast cancer dataset (normalized with MinMax scaling)
RBF-kernel SVC (with MinMax scaling) training set accuracy: 0.98
RBF-kernel SVC (with MinMax scaling) test set accuracy: 0.96


## Cross Validation

In [44]:
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier
import numpy as np
clf = KNeighborsClassifier(n_neighbors = 5)
X = X_fruits_2d.as_matrix()
y = y_fruits_2d.as_matrix()
cv_scores = cross_val_score(clf, X, y)

print('Cross-validation scores (3-fold):', cv_scores)
print('Mean cross-validation score (3-fold): {:.3f}'
     .format(np.mean(cv_scores)))

Cross-validation scores (3-fold): [0.77272727 0.73684211 0.83333333]
Mean cross-validation score (3-fold): 0.781


/home/ayush/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:5: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """
/home/ayush/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:6: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


## Decision Trees

In [46]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
#from adspy_shared_utilities import plot_decision_tree
from sklearn.model_selection import train_test_split


iris = load_iris()

X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, random_state = 3)
clf = DecisionTreeClassifier().fit(X_train, y_train)

print('Accuracy of Decision Tree classifier on training set: {:.2f}'
     .format(clf.score(X_train, y_train)))
print('Accuracy of Decision Tree classifier on test set: {:.2f}'
     .format(clf.score(X_test, y_test)))

Accuracy of Decision Tree classifier on training set: 1.00
Accuracy of Decision Tree classifier on test set: 0.95


### Setting max decision tree depth to help avoid overfitting

In [47]:
clf2 = DecisionTreeClassifier(max_depth = 3).fit(X_train, y_train)

print('Accuracy of Decision Tree classifier on training set: {:.2f}'
     .format(clf2.score(X_train, y_train)))
print('Accuracy of Decision Tree classifier on test set: {:.2f}'
     .format(clf2.score(X_test, y_test)))

Accuracy of Decision Tree classifier on training set: 0.98
Accuracy of Decision Tree classifier on test set: 0.97
